# Generated by Django 2.2.6 on 2021-10-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiopsSignatureAndPattern",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("model_id", models.CharField(max_length=128, verbose_name="模型ID")),
                ("signature", models.CharField(max_length=256, verbose_name="数据指纹")),
                ("pattern", models.TextField(verbose_name="pattern")),
            ],
            options={
                "index_together": {("model_id", "signature")},
            },
        ),
    ]
