# Generated by Django 2.2.6 on 2021-11-20 06:42

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0003_clusteringconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringconfig",
            name="bkdata_data_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="计算平台接入dataid"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="bkdata_etl_processing_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="计算平台清洗id"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="bkdata_etl_result_table_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="计算平台清洗结果表"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="log_bk_data_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="入库数据源"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="new_cls_pattern_rt",
            field=models.CharField(default="", max_length=255, verbose_name="新类结果表id"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="pre_treat_flow",
            field=django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="预处理flow配置"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="result_table_id",
            field=models.CharField(default="", max_length=255, verbose_name="结果表id"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="signature_enable",
            field=models.BooleanField(default=False, verbose_name="数据指纹开关"),
        ),
    ]
