# Generated by Django 2.2.6 on 2021-11-16 11:44

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0003_clusteringconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringconfig",
            name="bkdata_data_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="计算平台接入dataid"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="bkdata_etl_processing_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="计算平台清洗id"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="bkdata_etl_result_table_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="计算平台清洗结果表"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="etl_fields",
            field=django_jsonfield_backport.models.JSONField(default=None, verbose_name="清洗字段配置"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="etl_params",
            field=django_jsonfield_backport.models.JSONField(default=None, verbose_name="清洗配置"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="log_bk_data_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="入库数据源"),
        ),
    ]
