# Generated by Django 2.2.6 on 2021-11-22 01:52

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0004_auto_20211120_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringconfig",
            name="after_treat_flow",
            field=django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="after_treat_flow配置"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="after_treat_flow_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="预处理flowid"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="modify_flow",
            field=django_jsonfield_backport.models.JSONField(
                blank=True, null=True, verbose_name="修改after_treat_flow调用的配置"
            ),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="pre_treat_flow_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="预处理flowid"),
        ),
        migrations.AlterField(
            model_name="clusteringconfig",
            name="filter_rules",
            field=django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="过滤规则"),
        ),
    ]
