# Generated by Django 2.2.6 on 2021-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0005_auto_20211122_0952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clusteringconfig",
            name="result_table_id",
        ),
        migrations.AlterField(
            model_name="clusteringconfig",
            name="new_cls_pattern_rt",
            field=models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="新类结果表id"),
        ),
    ]
