# Generated by Django 2.2.6 on 2022-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0007_noticegroup_signaturestrategysettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaturestrategysettings",
            name="signature",
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name="数据指纹"),
        ),
    ]
