# Generated by Django 2.2.6 on 2022-01-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0008_auto_20220116_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticegroup",
            name="bk_biz_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="业务id"),
        ),
    ]
