# Generated by Django 2.2.6 on 2022-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0009_noticegroup_bk_biz_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturestrategysettings",
            name="pattern_level",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="聚类级别"),
        ),
    ]
