# Generated by Django 2.2.6 on 2022-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0010_signaturestrategysettings_pattern_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturestrategysettings",
            name="strategy_type",
            field=models.CharField(
                blank=True, default="normal_strategy", max_length=64, null=True, verbose_name="策略类型"
            ),
        ),
    ]
