# Generated by Django 2.2.6 on 2022-03-24 14:13

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0011_signaturestrategysettings_strategy_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringconfig",
            name="category_id",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="数据分类"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="es_storage",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="es 集群"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="python_backend",
            field=django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="模型训练配置"),
        ),
        migrations.AddField(
            model_name="clusteringconfig",
            name="source_rt_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="源rt名"),
        ),
    ]
