# Generated by Django 3.2.5 on 2022-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0011_signaturestrategysettings_strategy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiopsmodelexperiment",
            name="node_id_list",
            field=models.JSONField(blank=True, null=True, verbose_name="节点列表"),
        ),
        migrations.AlterField(
            model_name="clusteringconfig",
            name="after_treat_flow",
            field=models.JSONField(blank=True, null=True, verbose_name="after_treat_flow配置"),
        ),
        migrations.AlterField(
            model_name="clusteringconfig",
            name="filter_rules",
            field=models.JSONField(blank=True, null=True, verbose_name="过滤规则"),
        ),
        migrations.AlterField(
            model_name="clusteringconfig",
            name="modify_flow",
            field=models.JSONField(blank=True, null=True, verbose_name="修改after_treat_flow调用的配置"),
        ),
        migrations.AlterField(
            model_name="clusteringconfig",
            name="pre_treat_flow",
            field=models.JSONField(blank=True, null=True, verbose_name="预处理flow配置"),
        ),
    ]
