# Generated by Django 3.2.5 on 2022-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0013_auto_20220329_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusteringconfig",
            name="python_backend",
            field=models.JSONField(blank=True, null=True, verbose_name="模型训练配置"),
        ),
    ]
