# Generated by Django 3.2.5 on 2022-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0014_alter_clusteringconfig_python_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusteringconfig",
            name="after_treat_flow_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="模型应用flowid"),
        ),
    ]
