# Generated by Django 3.2.15 on 2023-03-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_clustering", "0017_clusteringsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiopssignatureandpattern", name="label", field=models.TextField(default="", verbose_name="备注"),
        ),
    ]
