settings:
  HEADER_CONFIG:
    zh: 日志平台 | 腾讯蓝鲸智云
    en: BK LOG | Tencent BlueKing
  TITLE_MENU_CONFIG:
    zh: 日志平台
    en: BK LOG
  EMAIL_TITLE:
    zh: 蓝鲸日志平台
    en: BLUEKING LOG
  MENU_LOGO_URL: images/open_icon.png
  FOOTER_CONFIG:
    footer:
      -
        zh:
          -
            text: 技术支持
            link: https://wpa1.qq.com/KziXGWJs?_type=wpa&qidian=true
          -
            text: 社区论坛
            link: https://bk.tencent.com/s-mart/community/
          -
            text: 产品官网
            link: https://bk.tencent.com/index/
        en:
          -
            text: Support
            link: https://wpa1.qq.com/KziXGWJs?_type=wpa&qidian=true
          -
            text: Forum
            link: https://bk.tencent.com/s-mart/community/
          -
            text: Official
            link: https://bk.tencent.com/index/
    copyright: Copyright © 2012-2021 Tencent BlueKing. All Rights Reserved.
  RUN_VER_DISPLAY:
    value: "{env.RUN_VER_DISPLAY}"
    env:
      RUN_VER_DISPLAY: "社区版"
  OAUTH_COOKIES_PARAMS:
    bk_token: bk_token
  INIT_SUPERUSER:
    - admin
  BK_DOC_URL: https://bk.tencent.com/docs/document/6.0/126/5817
  BK_DOC_QUERY_URL:
    value: "{env.BK_PAAS_HOST}/o/bk_docs_center{env.BKAPP_DOC_QUERY_URL}"
    env:
      BK_PAAS_HOST: ""
      BKAPP_DOC_QUERY_URL: /markdown/日志平台/产品白皮书/functions/addenda/query_string.md
  BK_DOC_DATA_URL:
    value: "{env.BK_PAAS_HOST}/o/bk_docs_center{env.BKAPP_DOC_DATA_URL}"
    env:
      BK_PAAS_HOST: ""
      BKAPP_DOC_DATA_URL: /markdown/基础计算平台/产品白皮书/intro/intro.md
  BKDATA_URL:
    value: "{env.BK_PAAS_HOST}/o/bk_dataweb"
    env:
      BK_PAAS_HOST: ""
  BK_FAQ_URL: https://bk.tencent.com/s-mart/community/question
  APIGW_ENABLED: true
  BK_SSM_HOST:
    value: "{env.BKAPP_BKSSM_HOST}"
    env:
     BKAPP_BKSSM_HOST: "bkssm.service.consul"
  BK_SSM_PORT:
    value: "{env.BKAPP_BKSSM_PORT}"
    env:
      BKAPP_BKSSM_PORT: "5000"
domains:
  ITSM_APIGATEWAY_ROOT_V2: "{settings.PAAS_API_HOST}/api/c/compapi/v2/itsm/"
  LOG_SEARCH_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v2/bk_log/"
  USER_MANAGE_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v2/usermanage/"
  BK_NODE_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v2/nodeman/"
  BK_PAAS_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v2/bk_paas/"
  BK_PAAS_V3_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/bkpaas3/prod/"
  ACCESS_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/data/v3/access/"
  STOREKIT_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/data/v3/storekit/"
  AUTH_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/data/v3/auth/"
  DATABUS_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/data/v3/databus/"
  DATAQUERY_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/data/v3/dataquery/"
  META_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/data/v3/meta/"
  CC_APIGATEWAY_ROOT_V2: "{settings.PAAS_API_HOST}/api/c/compapi/v2/cc/"
  CMSI_APIGATEWAY_ROOT_V2: "{settings.PAAS_API_HOST}/api/c/compapi/v2/cmsi/"
  GSE_APIGATEWAY_ROOT_V2: "{settings.PAAS_API_HOST}/api/c/compapi/v2/gse/"
  IAM_APIGATEWAY_ROOT_V2: "{settings.PAAS_API_HOST}/api/c/compapi/v2/iam/"
  JOB_APIGATEWAY_ROOT_V2: "{settings.PAAS_API_HOST}/api/c/compapi/v2/job/"
  MONITOR_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v2/monitor_v3/"
  BCS_CC_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/apigw/bcs-cc/prod/"
  BCS_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/apigw/bcs-api/prod/"
  BK_SSM_ROOT: "{settings.BK_SSM_HOST}:{settings.BK_SSM_PORT}/api/v1/auth/"
  AIOPS_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v3/aiops/"
  AIOPS_MODEL_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v3/model/"
  DATAFLOW_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v3/dataflow/flow/flows/"
  RESOURCE_CENTER_APIGATEWAY_ROOT: "{settings.PAAS_API_HOST}/api/c/compapi/v3/resourcecenter/"