# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-LOG 蓝鲸日志平台 available.
Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
BK-LOG 蓝鲸日志平台 is licensed under the MIT License.
License for BK-LOG 蓝鲸日志平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
# Generated by Django 1.11.23 on 2019-10-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0007_global_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessscenarioconfig",
            options={"verbose_name": "数据接入场景配置", "verbose_name_plural": "01_接入场景"},
        ),
        migrations.AlterModelOptions(
            name="accesssourceconfig",
            options={
                "ordering": ("-orders", "-source_id"),
                "verbose_name": "ES集群配置",
                "verbose_name_plural": "03_ES集群配置",
            },
        ),
        migrations.AlterModelOptions(
            name="logindexset",
            options={
                "ordering": ("-orders", "-index_set_id"),
                "verbose_name": "索引集配置",
                "verbose_name_plural": "21_索引集配置",
            },
        ),
        migrations.AlterModelOptions(
            name="logindexsetdata",
            options={"ordering": ("-index_id",), "verbose_name": "索引集数据", "verbose_name_plural": "22_索引集详情"},
        ),
        migrations.AlterModelOptions(
            name="projectinfo",
            options={"verbose_name": "项目列表", "verbose_name_plural": "02_项目列表"},
        ),
        migrations.AlterModelOptions(
            name="resourcechange",
            options={"verbose_name": "资源变更任务", "verbose_name_plural": "23_资源变更任务"},
        ),
        migrations.AlterModelOptions(
            name="userindexsetconfig",
            options={"verbose_name": "索引集自定义显示", "verbose_name_plural": "31_搜索-索引集自定义显示"},
        ),
        migrations.AddField(
            model_name="logindexset",
            name="collector_config_id",
            field=models.IntegerField(default=None, null=True, verbose_name="绑定Transfer采集ID"),
        ),
        migrations.AlterField(
            model_name="logindexset",
            name="source_id",
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="数据源ID"),
        ),
        migrations.AlterField(
            model_name="logindexsetdata",
            name="result_table_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="结果表名称"),
        ),
        migrations.AlterField(
            model_name="logindexsetdata",
            name="time_field",
            field=models.CharField(blank=True, default=True, max_length=64, null=True, verbose_name="时间字段"),
        ),
    ]
