# Generated by Django 2.2.6 on 2021-12-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0040_add_inner_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeatureToggle",
        ),
    ]
