# Generated by Django 2.2.6 on 2021-12-13 09:05

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0040_add_inner_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMetaConf",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("conf", django_jsonfield_backport.models.JSONField(default=dict, verbose_name="用户meta配置")),
                ("type", models.CharField(max_length=64, verbose_name="数据类型")),
            ],
            options={
                "verbose_name": "用户元配置",
                "verbose_name_plural": "44_用户元配置",
                "unique_together": {("username", "type")},
            },
        ),
        migrations.DeleteModel(
            name="FeatureToggle",
        ),
    ]
