# Generated by Django 2.2.6 on 2022-01-19 02:19

from django.db import migrations

from apps.log_search.constants import InnerTag, TagColor


def forwards_func(apps, schema_editor):
    tag_model = apps.get_model("log_search", "IndexSetTag")
    create_objs = [
        tag_model(
            name=InnerTag.CLUSTERING,
            color=TagColor.GREEN.value,
        ),
    ]
    tag_model.objects.bulk_create(create_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0041_auto_20211213_1705"),
    ]

    operations = [migrations.RunPython(forwards_func)]
