# Generated by Django 2.2.6 on 2022-01-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0042_auto_20220119_1019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asynctask",
            options={"verbose_name": "导出任务", "verbose_name_plural": "42_导出任务"},
        ),
        migrations.AddField(
            model_name="asynctask",
            name="bk_biz_id",
            field=models.IntegerField(default=None, null=True, verbose_name="业务ID"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="任务完成时间"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="end_time",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="导出选择结束时间"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="export_status",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="导出状态"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="export_type",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="导出类型"),
        ),
        migrations.AddField(
            model_name="asynctask",
            name="start_time",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="导出选择请求时间"),
        ),
        migrations.AlterModelTable(
            name="asynctask",
            table="export_task",
        ),
    ]
