# Generated by Django 3.2.5 on 2022-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0044_auto_20220329_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(default=None, null=True, verbose_name='业务ID')),
                ('biz_property_id', models.CharField(default='', max_length=64, null=True, verbose_name='业务属性ID')),
                ('biz_property_name', models.CharField(default='', max_length=64, null=True, verbose_name='业务属性名称')),
                ('biz_property_value', models.CharField(default='', max_length=256, null=True, verbose_name='业务属性值')),
            ],
            options={
                'verbose_name': '业务属性',
                'verbose_name_plural': '45_业务属性',
            },
        ),
    ]
