# Generated by Django 3.2.5 on 2022-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0045_bizproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindexset",
            name="bcs_project_id",
            field=models.IntegerField(default=0, verbose_name="项目ID"),
        ),
    ]
