# Generated by Django 3.2.5 on 2022-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0047_alter_logindexset_bcs_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesssourceconfig",
            name="space_uid",
            field=models.CharField(blank=True, default="", max_length=256, verbose_name="空间唯一标识"),
        ),
        migrations.AddField(
            model_name="favoritesearch",
            name="space_uid",
            field=models.CharField(blank=True, db_index=True, default="", max_length=256, verbose_name="空间唯一标识"),
        ),
        migrations.AddField(
            model_name="logindexset",
            name="space_uid",
            field=models.CharField(blank=True, db_index=True, default="", max_length=256, verbose_name="空间唯一标识"),
        ),
        migrations.AddField(
            model_name="resourcechange",
            name="space_uid",
            field=models.CharField(blank=True, db_index=True, default="", max_length=256, verbose_name="空间唯一标识"),
        ),
        migrations.AlterField(
            model_name="favoritesearch",
            name="project_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="项目ID"),
        ),
        migrations.AlterField(
            model_name="logindexset",
            name="project_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="项目ID"),
        ),
        migrations.AlterField(
            model_name="resourcechange",
            name="project_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="项目ID"),
        ),
    ]
