# Generated by Django 3.2.5 on 2022-08-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0049_project_id_to_space_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="空间自增ID")),
                ("space_uid", models.CharField(max_length=256, unique=True, verbose_name="空间唯一标识")),
                ("bk_biz_id", models.IntegerField(unique=True, verbose_name="业务ID")),
                ("space_type_id", models.CharField(max_length=64, verbose_name="空间类型英文名称")),
                ("space_type_name", models.CharField(max_length=64, verbose_name="空间类型中文名称")),
                ("space_id", models.CharField(max_length=128, verbose_name="空间 ID")),
                ("space_name", models.CharField(max_length=128, verbose_name="空间中文名称")),
                ("space_code", models.CharField(blank=True, max_length=64, null=True, verbose_name="空间英文名称")),
                ("properties", models.JSONField(default=dict, verbose_name="额外属性")),
            ],
            options={"verbose_name": "空间信息", "verbose_name_plural": "空间信息",},
        ),
        migrations.CreateModel(
            name="SpaceType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                (
                    "type_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="空间类型英文名称"),
                ),
                ("type_name", models.CharField(max_length=64, unique=True, verbose_name="空间类型中文名称")),
                ("properties", models.JSONField(default=dict, verbose_name="额外属性")),
            ],
            options={"verbose_name": "空间类型", "verbose_name_plural": "空间类型",},
        ),
    ]
