# Generated by Django 3.2.5 on 2022-09-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0048_logindexset_is_editable"),
        ("log_search", "0050_space_spacetype"),
    ]

    operations = []
