# Generated by Django 3.2.15 on 2022-10-16 18:32

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0051_merge_20220922_1505"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                (
                    "space_uid",
                    models.CharField(blank=True, db_index=True, default="", max_length=256, verbose_name="空间唯一标识"),
                ),
                ("index_set_id", models.IntegerField(verbose_name="索引集ID")),
                ("name", models.CharField(max_length=64, verbose_name="收藏名称")),
                ("group_id", models.IntegerField(db_index=True, verbose_name="收藏组ID")),
                ("params", apps.models.JsonField(default=None, null=True, verbose_name="检索条件")),
                (
                    "visible_type",
                    models.CharField(
                        choices=[("private", "个人可见"), ("public", "公开可见")], max_length=64, verbose_name="可见类型"
                    ),
                ),
                ("display_fields", models.JSONField(blank=True, default=None, verbose_name="显示字段")),
            ],
            options={
                "verbose_name": "检索收藏",
                "verbose_name_plural": "34_搜索-检索收藏",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="FavoriteGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("name", models.CharField(max_length=64, verbose_name="收藏组名称")),
                (
                    "group_type",
                    models.CharField(
                        choices=[("private", "个人组"), ("public", "公共组"), ("unknown", "未分组")],
                        max_length=64,
                        verbose_name="收藏组类型",
                    ),
                ),
                (
                    "space_uid",
                    models.CharField(blank=True, db_index=True, default="", max_length=256, verbose_name="空间唯一标识"),
                ),
            ],
            options={
                "verbose_name": "检索收藏组",
                "verbose_name_plural": "34_搜索-检索收藏组",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="FavoriteGroupCustomOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "space_uid",
                    models.CharField(blank=True, db_index=True, default="", max_length=256, verbose_name="空间唯一标识"),
                ),
                ("username", models.CharField(db_index=True, max_length=255, verbose_name="用户名")),
                ("group_order", models.JSONField(blank=True, null=True, verbose_name="用户自定义收藏组ID顺序")),
            ],
            options={
                "verbose_name": "用户检索收藏组顺序",
                "verbose_name_plural": "34_搜索-用户检索收藏组顺序",
            },
        ),
        migrations.AlterModelOptions(
            name="favoritesearch",
            options={},
        ),
    ]
