# Generated by Django 3.2.15 on 2022-10-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0052_auto_20221017_0232"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="is_enable_display_fields",
            field=models.BooleanField(default=False, verbose_name="是否同时显示字段"),
        ),
    ]
