# Generated by Django 3.2.15 on 2022-11-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0056_alter_favoritegroup_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="favoritegroup",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="favoritegroup",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="favoritegroup",
            name="is_deleted",
        ),
    ]
