# Generated by Django 3.2.15 on 2022-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0057_auto_20221101_1547"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="name",
            field=models.CharField(max_length=255, verbose_name="收藏名称"),
        ),
    ]
