# Generated by Django 3.2.15 on 2022-11-29 11:02

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0059_migrate_old_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIndexSetFieldsConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index_set_id", models.IntegerField(db_index=True, verbose_name="索引集ID")),
                ("config_id", models.IntegerField(db_index=True, verbose_name="索引集ID")),
                ("username", models.CharField(db_index=True, default="", max_length=32, verbose_name="用户名")),
            ],
            options={
                "verbose_name": "用户索引集配置",
                "verbose_name_plural": "31_搜索-用户索引集配置",
                "unique_together": {("index_set_id", "username")},
            },
        ),
        migrations.CreateModel(
            name="IndexSetFieldsConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="配置名称")),
                ("index_set_id", models.IntegerField(db_index=True, verbose_name="索引集ID")),
                ("display_fields", apps.models.JsonField(verbose_name="字段配置")),
                ("sort_list", apps.models.JsonField(default=None, null=True, verbose_name="排序规则")),
            ],
            options={
                "verbose_name": "索引集自定义显示",
                "verbose_name_plural": "31_搜索-索引集自定义显示",
                "unique_together": {("index_set_id", "name")},
            },
        ),
    ]
