# Generated by Django 3.2.15 on 2023-01-10 09:40

from django.db import migrations, models
from apps.log_search.constants import FavoriteGroupType


def forwards_func(apps, schema_editor):
    favorite_group_model = apps.get_model("log_search", "FavoriteGroup")

    # 将个人组的名称统一修改为新的个人组名称
    groups = favorite_group_model.objects.filter(group_type=FavoriteGroupType.PRIVATE.value).all()
    for group in groups:
        group.name = FavoriteGroupType.get_choice_label(str(FavoriteGroupType.PRIVATE.value))
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0061_migrate_old_userindexconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritegroup",
            name="group_type",
            field=models.CharField(
                choices=[("private", "个人收藏"), ("public", "公共组"), ("unknown", "未分组")],
                max_length=64,
                verbose_name="收藏组类型",
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
