# Generated by Django 3.2.15 on 2023-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_search", "0062_rename_private_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space", name="space_uid", field=models.CharField(max_length=256, verbose_name="空间唯一标识"),
        ),
    ]
