# Generated by Django 3.2.5 on 2022-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_toggle", "0002_auto_20210714_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuretoggle",
            name="biz_id_white_list",
            field=models.JSONField(blank=True, null=True, verbose_name="业务白名单"),
        ),
        migrations.AlterField(
            model_name="featuretoggle",
            name="feature_config",
            field=models.JSONField(blank=True, null=True, verbose_name="特性开关配置"),
        ),
    ]
