# Generated by Django 3.2.5 on 2022-04-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_toggle', '0003_auto_20220329_1717'),
        ('feature_toggle', '0004_add_es_cluster_doc_20220408_1740'),
    ]

    operations = [
    ]
