# Generated by Django 2.2.6 on 2021-08-21 01:50

from django.db import migrations

from apps.utils.log import logger
from apps.log_measure.constants import DATA_NAMES, BK_MONITOR_CLIENT


def forwards_func(apps, schema_editor):
    try:
        BK_MONITOR_CLIENT.custom_metric().migrate(data_name_list=Migration.data_names)
    except Exception as e:  # pylint: disable=broad-except
        logger.error(f"custom_metric migrate error: {e}")


class Migration(migrations.Migration):
    data_names = DATA_NAMES
    dependencies = [
        ("log_measure", "0004_init_custom_metric"),
    ]

    operations = [migrations.RunPython(forwards_func)]
