# Generated by Django 2.2.6 on 2021-08-21 01:50

from django.db import migrations


from apps.utils.log import logger
from apps.log_measure.constants import DATA_NAMES, BK_MONITOR_CLIENT, BK_LOG_EVENT_DATA_NAME
from bk_monitor.constants import EVENT_TYPE


def forwards_func(apps, schema_editor):
    try:
        BK_MONITOR_CLIENT.custom_metric().migrate(
            data_name_list=[BK_LOG_EVENT_DATA_NAME], custom_report_type=EVENT_TYPE
        )
    except Exception as e:  # pylint: disable=broad-except
        logger.error(f"custom_metric migrate error: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ("log_measure", "0006_add_django_monitor"),
    ]

    operations = [migrations.RunPython(forwards_func)]
