# Generated by Django 3.2.5 on 2022-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_measure', '0008_auto_20211209_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessindexset',
            name='space_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='空间唯一标识'),
        ),
        migrations.AlterUniqueTogether(
            name='accessindexset',
            unique_together={('space_uid', 'index_set_id', 'static_date', 'created_by')},
        ),
    ]
