#!/bin/sh

export LAN_IP="__LAN_IP__"
export BKLOG_API_PORT="__BK_BKLOG_API_PORT__"

# 导入虚拟环境
export PATH=__BK_HOME__/.envs/bklog-api/bin:$PATH

# PaaS 相关配置
export BK_PAAS_HOST="__BK_PAAS_PUBLIC_URL__"
export BK_PAAS_INNER_HOST="__BK_PAAS_PRIVATE_URL__"

# APP 配置
export BK_ENV="production"
export BK_LOG_DIR="__BK_HOME__/logs/bklog"
export DJANGO_SETTINGS_MODULE="settings"

# APP 凭证信息
export APP_ID="__BK_BKLOG_APP_CODE__"
export APP_TOKEN="__BK_BKLOG_APP_SECRET__"

# MySQL 信息
export DB_NAME="bk_log_search"
export DB_USERNAME="__BK_PAAS_MYSQL_USER__"
export DB_PASSWORD="__BK_PAAS_MYSQL_PASSWORD__"
export DB_HOST="__BK_PAAS_MYSQL_HOST__"
export DB_PORT="__BK_PAAS_MYSQL_PORT__"

# Consul 信息
export CONSUL_CLIENT_CERT_FILE_PATH="__BK_HOME__/cert/__BK_CONSUL_CLIENT_CERT_FILE__"
export CONSUL_CLIENT_KEY_FILE_PATH="__BK_HOME__/cert/__BK_CONSUL_CLIENT_KEY_FILE__"
export CONSUL_SERVER_CA_CERT_PATH="__BK_HOME__/cert/__BK_CONSUL_CA_FILE__"
export CONSUL_HTTPS_PORT="__BK_CONSUL_HTTPS_PORT__"

# IAM
export BK_IAM_V3_INNER_HOST="http://__BK_IAM_PRIVATE_ADDR__"
export BK_IAM_V3_APP_CODE="bk_iam"

# 后台API模块
export BKAPP_IS_BKLOG_API="1"

# grafana
export BKAPP_GRAFANA_URL="http://__BK_BKLOG_GRAFANA_HOST__:__BK_BKLOG_GRAFANA_PORT__"

# redis
export BK_BKLOG_REDIS_HOST=__BK_BKLOG_REDIS_HOST__
export BK_BKLOG_REDIS_PORT=__BK_BKLOG_REDIS_PORT__
export BK_BKLOG_REDIS_MODE=__BK_BKLOG_REDIS_MODE__
export BK_BKLOG_REDIS_PASSWORD=__BK_BKLOG_REDIS_PASSWORD__
export BK_BKLOG_REDIS_SENTINEL_HOST=__BK_BKLOG_REDIS_SENTINEL_HOST__
export BK_BKLOG_REDIS_SENTINEL_PORT=__BK_BKLOG_REDIS_SENTINEL_PORT__
export BK_BKLOG_REDIS_SENTINEL_MASTER_NAME=__BK_BKLOG_REDIS_SENTINEL_MASTER_NAME__
export BK_BKLOG_REDIS_SENTINEL_MASTER_PASSWORD=__BK_BKLOG_REDIS_SENTINEL_MASTER_PASSWORD__