# Generated by Django 2.2.6 on 2021-04-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitorReportConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_id", models.IntegerField(blank=True, null=True, verbose_name="监控数据源id")),
                ("data_name", models.CharField(max_length=64, unique=True, verbose_name="数据源名称")),
                ("bk_biz_id", models.IntegerField(verbose_name="指定业务id")),
                ("table_id", models.CharField(blank=True, max_length=128, null=True, verbose_name="结果表名")),
                ("access_token", models.CharField(blank=True, max_length=128, null=True, verbose_name="数据上报token")),
                ("is_enable", models.BooleanField(default=True, verbose_name="数据源是否enable")),
            ],
            options={
                "verbose_name": "运营数据上报配置",
                "verbose_name_plural": "运营数据上报配置",
            },
        ),
    ]
