# Generated by Django 2.2.6 on 2021-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorreportconfig",
            name="custom_report_type",
            field=models.CharField(
                choices=[("time_series", "时序数据"), ("event", "事件数据")],
                default="time_series",
                max_length=20,
                verbose_name="类型",
            ),
        ),
    ]
