# Generated by Django 3.2.5 on 2022-08-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bk_monitor", "0002_monitorreportconfig_custom_report_type"),
        ("bk_monitor", "0003_update_dataid"),
    ]

    operations = []
