# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-LOG 蓝鲸日志平台 available.
Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
BK-LOG 蓝鲸日志平台 is licensed under the MIT License.
License for BK-LOG 蓝鲸日志平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
We undertake not to change the open source license (MIT license) applicable to the current version of
the project delivered to anyone in the future.
"""
# Generated by Django 1.11.23 on 2020-07-01 06:24
from __future__ import unicode_literals

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_extract", "0002_auto_20200621_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategies",
            name="file_type",
            field=apps.models.MultiStrSplitByCommaFieldText(verbose_name="文件类型"),
        ),
        migrations.AlterField(
            model_name="strategies",
            name="modules",
            field=apps.models.JsonField(verbose_name="模块列表"),
        ),
        migrations.AlterField(
            model_name="strategies",
            name="select_type",
            field=models.CharField(max_length=16, verbose_name="目标选择类型"),
        ),
        migrations.AlterField(
            model_name="strategies",
            name="user_list",
            field=apps.models.MultiStrSplitByCommaFieldText(verbose_name="用户组ID"),
        ),
        migrations.AlterField(
            model_name="strategies",
            name="visible_dir",
            field=apps.models.MultiStrSplitByCommaFieldText(verbose_name="目录列表"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="cstone_download_task_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="云石任务ID"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="cstone_download_ticket",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="下载票据"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="cstone_upload_task_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="云石上传ID"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="cstone_upload_ticket",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="上传票据"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="download_status",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="当前文件下载状态"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="filter_type",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="过滤类型"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="job_task_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="文件分发ID"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="job_upload_task_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="任务上传ID"),
        ),
    ]
