# Generated by Django 2.2.6 on 2021-07-05 09:29

import apps.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_extract", "0022_auto_20210622_1721"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategies",
            name="group_id",
        ),
        migrations.AlterField(
            model_name="strategies",
            name="user_list",
            field=apps.models.MultiStrSplitByCommaFieldText(verbose_name="用户ID"),
        ),
    ]
