# Generated by Django 2.2.6 on 2021-09-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TraceDatasourceMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("index_set_id", models.IntegerField(verbose_name="trace索引集id")),
                ("datasource_id", models.IntegerField(unique=True, verbose_name="数据源id")),
            ],
        ),
    ]
