# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-LOG 蓝鲸日志平台 available.
Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
BK-LOG 蓝鲸日志平台 is licensed under the MIT License.
License for BK-LOG 蓝鲸日志平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
# Generated by Django 1.11.23 on 2020-10-14 09:17
from __future__ import unicode_literals

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0006_auto_20200605_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLinkConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("data_link_id", models.AutoField(primary_key=True, serialize=False, verbose_name="链路ID")),
                ("link_group_name", models.CharField(max_length=64, verbose_name="集群名称")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("kafka_cluster_id", models.IntegerField(verbose_name="kafka集群ID")),
                ("transfer_cluster_id", models.CharField(max_length=128, verbose_name="transfer集群ID")),
                ("es_cluster_ids", apps.models.JsonField(default=[], null=True, verbose_name="es集群ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否可用")),
                ("description", models.TextField(default="", verbose_name="备注")),
            ],
            options={
                "verbose_name": "数据链路配置",
                "verbose_name_plural": "数据链路配置",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="data_link_id",
            field=models.IntegerField(default=None, null=True, verbose_name="采集链路id"),
        ),
    ]
