# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-LOG 蓝鲸日志平台 available.
Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
BK-LOG 蓝鲸日志平台 is licensed under the MIT License.
License for BK-LOG 蓝鲸日志平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
We undertake not to change the open source license (MIT license) applicable to the current version of
the project delivered to anyone in the future.
"""
# Generated by Django 2.2.6 on 2021-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0010_auto_20201215_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="collector_output_format",
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name="输出格式"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="collector_package_count",
            field=models.IntegerField(default=10, null=True, verbose_name="采集打包数量"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="storage_replies",
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name="ES副本数"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="storage_shards_nums",
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="ES分片数量"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="storage_shards_size",
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="单shards分片大小"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="can_use_independent_es_cluster",
            field=models.BooleanField(blank=True, default=True, verbose_name="是否能够使用独立es集群"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="collector_scenario_id",
            field=models.CharField(max_length=64, verbose_name="采集场景"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="itsm_ticket_sn",
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="itsm单据号"),
        ),
    ]
