# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-LOG 蓝鲸日志平台 available.
Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
BK-LOG 蓝鲸日志平台 is licensed under the MIT License.
License for BK-LOG 蓝鲸日志平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
# Generated by Django 2.2.6 on 2021-08-10 06:32

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0013_auto_20210524_1453"),
    ]

    operations = [
        migrations.CreateModel(
            name="BKDataClean",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("status", models.CharField(max_length=64, verbose_name="状态")),
                ("status_en", models.CharField(max_length=64, verbose_name="状态英文名")),
                ("result_table_id", models.CharField(db_index=True, max_length=128, verbose_name="结果表id")),
                ("result_table_name", models.CharField(max_length=128, verbose_name="结果表名")),
                (
                    "result_table_name_alias",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="结果表中文名"),
                ),
                ("raw_data_id", models.IntegerField(db_index=True, verbose_name="数据源id")),
                ("data_name", models.CharField(max_length=128, verbose_name="数据源名称")),
                ("data_alias", models.CharField(blank=True, max_length=128, null=True, verbose_name="数据源中文名")),
                ("data_type", models.CharField(max_length=64, verbose_name="数据类型")),
                ("storage_type", models.CharField(max_length=64, verbose_name="存储类型")),
                ("storage_cluster", models.CharField(max_length=64, verbose_name="存储集群")),
                ("collector_config_id", models.IntegerField(db_index=True, verbose_name="采集项id")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("log_index_set_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="索引集id")),
                ("is_authorized", models.BooleanField(default=False, verbose_name="索引集是否被授权")),
            ],
            options={
                "verbose_name": "高级清洗列表",
                "verbose_name_plural": "高级清洗列表",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="CleanStash",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("clean_stash_id", models.AutoField(primary_key=True, serialize=False, verbose_name="清洗缓存id")),
                ("clean_type", models.CharField(max_length=64, verbose_name="模板类型")),
                ("etl_params", django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="etl配置")),
                ("etl_fields", django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="etl字段")),
                ("collector_config_id", models.IntegerField(db_index=True, verbose_name="采集项列表")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
            ],
            options={
                "verbose_name": "未完成入库暂存清洗",
                "verbose_name_plural": "未完成入库暂存清洗",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="CleanTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("clean_template_id", models.AutoField(primary_key=True, serialize=False, verbose_name="清洗id")),
                ("name", models.CharField(max_length=128, verbose_name="模板名")),
                ("clean_type", models.CharField(max_length=64, verbose_name="模板类型")),
                ("etl_params", django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="etl配置")),
                ("etl_fields", django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name="etl字段")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
            ],
            options={
                "verbose_name": "清洗模板",
                "verbose_name_plural": "清洗模板",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="collector_config_name_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="采集项英文名"),
        ),
    ]
