# Generated by Django 2.2.6 on 2021-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0014_auto_20210802_1630"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bkdataclean",
            name="log_index_set_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="索引集id"),
        ),
    ]
