# Generated by Django 2.2.6 on 2021-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0015_auto_20210813_1148"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("archive_config_id", models.AutoField(primary_key=True, serialize=False, verbose_name="归档配置id")),
                ("collector_config_id", models.IntegerField(verbose_name="关联采集项id")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("snapshot_days", models.IntegerField(default=0, verbose_name="快照天数")),
                (
                    "target_snapshot_repository_name",
                    models.CharField(default="", max_length=255, verbose_name="快照仓库名称"),
                ),
            ],
            options={
                "verbose_name": "归档配置表",
                "verbose_name_plural": "归档配置表",
            },
        ),
        migrations.CreateModel(
            name="RestoreConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("restore_config_id", models.AutoField(primary_key=True, serialize=False, verbose_name="采集配置ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务id")),
                ("archive_config_id", models.IntegerField(verbose_name="归档id")),
                ("meta_restore_id", models.IntegerField(default=None, null=True, verbose_name="meta回溯id")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("expired_time", models.DateTimeField(verbose_name="到期时间")),
                ("is_done", models.BooleanField(default=False, verbose_name="是否完成")),
                ("duration", models.IntegerField(default=-1, verbose_name="耗时")),
                ("total_store_size", models.BigIntegerField(default=None, null=True, verbose_name="存储大小")),
                ("total_doc_count", models.BigIntegerField(default=None, null=True, verbose_name="文档数量")),
                ("index_set_name", models.CharField(max_length=64, verbose_name="索引集名称")),
                ("index_set_id", models.IntegerField(default=None, null=True, verbose_name="索引集id")),
                ("notice_user", models.TextField(verbose_name="结果通知人")),
            ],
            options={
                "verbose_name": "回溯配置表",
                "verbose_name_plural": "回溯配置表",
            },
        ),
    ]
