# Generated by Django 2.2.6 on 2021-08-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0015_auto_20210804_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bkdataclean",
            name="data_alias",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="数据源中文名"),
        ),
        migrations.AlterField(
            model_name="bkdataclean",
            name="result_table_id",
            field=models.CharField(db_index=True, max_length=128, verbose_name="结果表id"),
        ),
        migrations.AlterField(
            model_name="bkdataclean",
            name="result_table_name_alias",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="结果表中文名"),
        ),
    ]
