# Generated by Django 3.2.5 on 2022-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0017_auto_20211209_1848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanstash",
            name="etl_fields",
            field=models.JSONField(blank=True, null=True, verbose_name="etl字段"),
        ),
        migrations.AlterField(
            model_name="cleanstash",
            name="etl_params",
            field=models.JSONField(blank=True, null=True, verbose_name="etl配置"),
        ),
        migrations.AlterField(
            model_name="cleantemplate",
            name="etl_fields",
            field=models.JSONField(blank=True, null=True, verbose_name="etl字段"),
        ),
        migrations.AlterField(
            model_name="cleantemplate",
            name="etl_params",
            field=models.JSONField(blank=True, null=True, verbose_name="etl配置"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="collector_config_overlay",
            field=models.JSONField(blank=True, default=None, max_length=32, null=True, verbose_name="采集器配置覆盖"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="custom_type",
            field=models.CharField(
                choices=[("log", "容器日志上报"), ("otlp_trace", "otlpTrace上报"), ("otlp_log", "otlp日志上报")],
                default="log",
                max_length=30,
                verbose_name="自定义类型",
            ),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="target_node_type",
            field=models.CharField(
                choices=[
                    ("TOPO", "TOPO"),
                    ("INSTANCE", "主机实例"),
                    ("SERVICE_TEMPLATE", "服务模板"),
                    ("SET_TEMPLATE", "集群模板"),
                    ("DYNAMIC_GROUP", "动态分组"),
                ],
                default="INSTANCE",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
    ]
