# Generated by Django 3.2.5 on 2022-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0018_auto_20220329_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageused",
            name="biz_count",
            field=models.IntegerField(default=0, verbose_name="业务数量"),
        ),
        migrations.AddField(
            model_name="storageused",
            name="index_count",
            field=models.IntegerField(default=0, verbose_name="索引数量"),
        ),
        migrations.AddField(
            model_name="storageused",
            name="storage_total",
            field=models.BigIntegerField(default=0, verbose_name="总容量"),
        ),
        migrations.AddField(
            model_name="storageused",
            name="storage_usage",
            field=models.IntegerField(default=0, verbose_name="容量使用率"),
        ),
        migrations.AlterField(
            model_name="storageused",
            name="storage_used",
            field=models.FloatField(default=0, verbose_name="已用容量"),
        ),
    ]
