# Generated by Django 3.2.5 on 2022-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_databus", "0020_itsmetlconfig"),
    ]
    operations = [
        migrations.AddField(
            model_name="cleantemplate",
            name="visible_bk_biz_id",
            field=models.TextField(default="", verbose_name="可见业务ID"),
        ),
        migrations.AddField(
            model_name="cleantemplate",
            name="visible_type",
            field=models.CharField(default="current_biz", max_length=64, verbose_name="可见类型"),
        ),
    ]
