# Generated by Django 3.2.5 on 2022-05-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0022_alter_cleantemplate_visible_bk_biz_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerCollectorConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("collector_config_id", models.IntegerField(db_index=True, verbose_name="采集项id")),
                ("namespaces", models.JSONField(blank=True, null=True, verbose_name="namespace选择")),
                ("any_namespace", models.BooleanField(default=False, verbose_name="所有namespace")),
                ("data_encoding", models.CharField(default=None, max_length=30, null=True, verbose_name="日志字符集")),
                ("params", models.JSONField(blank=True, null=True, verbose_name="params")),
                ("workload_type", models.CharField(blank=True, max_length=128, null=True, verbose_name="应用类型")),
                ("workload_name", models.CharField(blank=True, max_length=128, null=True, verbose_name="应用名称")),
                ("container_name", models.CharField(blank=True, max_length=128, null=True, verbose_name="容器名")),
                ("match_labels", models.JSONField(blank=True, null=True, verbose_name="匹配标签")),
                ("match_expressions", models.JSONField(blank=True, null=True, verbose_name="匹配表达式")),
                ("all_container", models.BooleanField(default=False, verbose_name="所有容器")),
                ("status", models.CharField(blank=True, max_length=30, null=True, verbose_name="下发状态")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="add_pod_label",
            field=models.BooleanField(default=False, verbose_name="是否自动添加pod中的labels"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="bcs_cluster_id",
            field=models.IntegerField(default=0, verbose_name="bcs集群id"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="environment",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="环境"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="extra_labels",
            field=models.JSONField(blank=True, null=True, verbose_name="额外字段添加"),
        ),
    ]
