# Generated by Django 3.2.5 on 2022-05-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0023_auto_20220506_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectorconfig",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务id"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="bkdata_biz_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="数据归属业务ID"),
        ),
        migrations.AlterField(
            model_name="collectorplugin",
            name="bk_biz_id",
            field=models.BigIntegerField(verbose_name="业务id"),
        ),
    ]
