# Generated by Django 3.2.5 on 2022-05-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0023_auto_20220524_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectorconfig",
            name="bcs_cluster_id",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="bcs集群id"),
        ),
    ]
