# Generated by Django 3.2.5 on 2022-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0024_alter_collectorconfig_bcs_cluster_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="yaml_config",
            field=models.TextField(default="", verbose_name="yaml配置内容"),
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="yaml_config_enabled",
            field=models.BooleanField(default=False, verbose_name="是否使用yaml配置模式"),
        ),
        migrations.AddField(
            model_name="containercollectorconfig",
            name="collector_type",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="容器采集类型"),
        ),
        migrations.AlterField(
            model_name="containercollectorconfig",
            name="status",
            field=models.CharField(
                blank=True, choices=[("SUCCESS", "成功"), ("FAILED", "失败")], max_length=30, null=True, verbose_name="下发状态"
            ),
        ),
    ]
