# Generated by Django 3.2.5 on 2022-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0026_set_collector_config_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BcsRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("deleted_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="删除者")),
                ("rule_name", models.CharField(max_length=64, verbose_name="采集配置名称")),
                ("bcs_project_id", models.IntegerField(default=0, verbose_name="项目ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collectorconfig",
            name="rule_id",
            field=models.IntegerField(default=0, verbose_name="bcs规则集id"),
        ),
        migrations.AddField(
            model_name="containercollectorconfig",
            name="parent_container_config_id",
            field=models.IntegerField(default=0, verbose_name="父配置id"),
        ),
        migrations.AddField(
            model_name="containercollectorconfig",
            name="rule_id",
            field=models.IntegerField(default=0, verbose_name="bcs规则集id"),
        ),
        migrations.AlterField(
            model_name="containercollectorconfig",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("SUCCESS", "成功"), ("FAILED", "失败"), ("TERMINATED", "已停用")],
                max_length=30,
                null=True,
                verbose_name="下发状态",
            ),
        ),
    ]
