# Generated by Django 3.2.5 on 2022-07-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0024_auto_20220510_1434"),
        ("log_databus", "0027_auto_20220706_0012"),
    ]

    operations = []
