# Generated by Django 3.2.5 on 2022-07-21 06:32

from django.db import migrations


def forwards_func(apps, schema_editor):
    collector_config = apps.get_model("log_databus", "CollectorConfig")
    collector_config.objects.filter(bcs_cluster_id="0").update(bcs_cluster_id="")


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0029_alter_bcsrule_bcs_project_id"),
    ]

    operations = [migrations.RunPython(forwards_func)]
