# Generated by Django 3.2.5 on 2022-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0030_auto_20220721_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorplugin",
            name="index_settings",
            field=models.JSONField(default=dict, verbose_name="索引Settings"),
        ),
    ]
