# Generated by Django 3.2.15 on 2022-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0031_collectorplugin_index_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorconfig",
            name="log_group_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="自定义日志组ID"),
        ),
    ]
