# Generated by Django 3.2.15 on 2022-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0032_auto_20221129_1545"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="collectorconfig",
            index_together={("custom_type", "log_group_id")},
        ),
    ]
