# Generated by Django 3.2.15 on 2023-02-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0032_auto_20221209_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="collector_plugin_id",
            field=models.IntegerField(null=True, verbose_name="关联采集插件id"),
        ),
        migrations.AlterField(
            model_name="archiveconfig",
            name="collector_config_id",
            field=models.IntegerField(null=True, verbose_name="关联采集项id"),
        ),
    ]
