# Generated by Django 3.2.15 on 2023-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_databus", "0033_auto_20230206_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="containercollectorconfig",
            name="status_detail",
            field=models.TextField(blank=True, default="", verbose_name="状态详情"),
        ),
        migrations.AlterField(
            model_name="collectorconfig",
            name="target_node_type",
            field=models.CharField(
                choices=[
                    ("TOPO", "拓扑"),
                    ("INSTANCE", "主机实例"),
                    ("SERVICE_TEMPLATE", "服务模板"),
                    ("SET_TEMPLATE", "集群模板"),
                    ("DYNAMIC_GROUP", "动态分组"),
                ],
                default="INSTANCE",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
        migrations.AlterField(
            model_name="containercollectorconfig",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "等待中"),
                    ("RUNNING", "部署中"),
                    ("SUCCESS", "成功"),
                    ("FAILED", "失败"),
                    ("TERMINATED", "已停用"),
                ],
                max_length=30,
                null=True,
                verbose_name="下发状态",
            ),
        ),
    ]
