# Generated by Django 3.2.15 on 2022-12-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPChooserConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=255, verbose_name="用户名")),
                ("config", models.JSONField(blank=True, null=True, verbose_name="配置")),
            ],
        ),
    ]
